CREATE TABLE Usuarios(
    id int(11) NOT NULL,
    nombre varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO Usuarios(id, nombre) VALUES (435, 'NELSON ALEXANDER BRIZUELA RAMIREZ');
INSERT INTO Usuarios(id, nombre) VALUES (552, 'RICARDO MENDEZ LORCA');
INSERT INTO Usuarios(id, nombre) VALUES (125, 'GERMAN MILLAN LEAL');
INSERT INTO Usuarios(id, nombre) VALUES (999, 'CARMEN YANES BENITEZ');
